### ISSUE TITLE
Add vxdataprocessor metrics to our prometheous and alert servicer on adb-cb1 and create a graphana panel.

### ISSUE THREAD

**Issue by randytpierce** [NOAA-GSL/vxDataProcessor#64]
We need to incorporate the vxdataprocessor metrics into our Prometheus framework.

**Comment by randytpierce** [comment]
We modified the vx-prometheus config to include the go metrics scraper that Ian found and then we added a public domain dashboard to our graphana service http://adb-cb1.gsd.esrl.noaa.gov:3000/

It works and it is very interesting in that it has already shown us that we are retaining a certain number of goroutines when we process scorecards. So that is a bug, although not a high priority.

**Comment by randytpierce** [comment]
I think we can close this at our next issue review and we can create another issue if we want to add alerts later.

**Comment by ian-noaa** [comment]
A quick screenshot showing some of the functionality.

![image](https://user-images.githubusercontent.com/67600557/233734174-d6b13842-39ab-49f5-aed0-7ae802581125.png)
